services:
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server --console-address ":9001" /data
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - .env

networks:
  minio:
    name: minio
